title: Brooke (Xuchen) Gong
logo: files/riding.jpg
description: xg54@duke.edu / [LinkIn](https://www.linkedin.com/in/xuchen-gong-563a06176/)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
