title: Brooke (Xuchen) Gong
# description: "Email: xg54 at duke dot edu"
logo: files/riding.jpg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
markdown: GFM
github:
  owner_url: https://github.com/brookekekeboom
